apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meu-replicaset
  namespace: meunamespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: meuapp
  template:
    metadata:
      labels:
        app: meuapp
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
