apiVersion: batch/v1
kind: Job
metadata:
  name: meu-job
  namespace: meunamespace
spec:
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - name: meu-container
        image: busybox
        command: ["echo", "Executando um Job"]
      restartPolicy: OnFailure
