apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meu-pvc
  namespace: meunamespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
