apiVersion: batch/v1
kind: CronJob
metadata:
  name: meu-cronjob
  namespace: meunamespace
spec:
  schedule:
    - cron: 0 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: meu-container
            image: busybox
            command: ["echo", "Executando um CronJob"]
          restartPolicy: OnFailure
